### ISSUE TITLE
Stubbing multiple parameter captures

### ISSUE THREAD

**Issue by elazar** [mlively/Phake#148]
I ran into an issue where it doesn't appear to be possible to stub the same method multiple times to do a parameter capture if there are no differing non-captured parameters between invocations.

My use case involves using a mock event emitter, which the code under test uses to emit the same event multiple times over the course of the test. My purpose was to capture the event parameters to verify them.

**Comment by mlively** [comment]
This is now possible using Phake::captureAll()

```
$mock = Phake::mock('PhakeTest_MockedClass');

$obj1 = new stdClass;
$obj2 = new stdClass;
$obj3 = new stdClass;

$mock->fooWithArgument($obj1);
$mock->fooWithArgument($obj2);
$mock->fooWithArgument($obj3);

Phake::verify($mock, Phake::atLeast(1))->fooWithArgument(Phake::captureAll($toArgument));

$this->assertSame(array($obj1, $obj2, $obj3), $toArgument);
```

Also documented usage at the bottom of this section: http://phake.readthedocs.org/en/2.1/method-parameter-matchers.html#parameter-capturing

Available in the 2.1 dev branch
