### ISSUE TITLE
Phake::inOrder fails when verifying multiple calls with the same parameters

### ISSUE THREAD

**Issue by kastermester** [mlively/Phake#151]
See below test code, I would expect it to work, but it fails with the following message:

```
1) SomeTest::testPhake
Failed asserting that Expected Something->write(equal to <string:1>) to be called exactly <1> times, actually called <2> times.
Other Invocations:
  Something->write(<string:2>).
```

```php
interface Something {
	function write($test);
}

class SomeTest extends PHPUnit_Framework_TestCase {
	public function testPhake(){
		$phake = Phake::mock('Something');
		$phake->write('1');
		$phake->write('2');
		$phake->write('1');

		Phake::inOrder(
			Phake::verify($phake)->write('1'),
			Phake::verify($phake)->write('2'),
			Phake::verify($phake)->write('1')
		);
	}
}
```

**Comment by mlively** [comment]
In these cases I would recommend doing something along the lines of:

    Phake::inOrder(
        Phake::verify($phake, Phake::atLeast(1))->write('1'),
        Phake::verify($phake, Phake::atLeast(1))->write('2'),
        Phake::verify($phake, Phake::atLeast(1))->write('1')
    );

I am open to having something built in to do this, but I am having a tough time thinking of a syntax that makes sense and doesn't introduce risk to other tests. If you have any recommendations feel free to re-open.
