### ISSUE TITLE
Documentation on custom answers is wrong

### ISSUE THREAD

**Issue by ruafozy** [mlively/Phake#153]
Forgive me if I'm being stupid, but there seems to be an error in
http://phake.readthedocs.org/en/latest/answers.html, in the section headed
"Custom Answers".  The section begins by talking about custom answers,
but suddenly switches to talking about custom *argument matchers*.

**Comment by mlively** [comment]
You are correct. I have no idea what happened with that documentation. I am actually getting rid of that section of the docs altogether and documenting using callbacks.
