### ISSUE TITLE
Allow direct calling of protected methods for mocks

### ISSUE THREAD

**Issue by duclet** [mlively/Phake#158]
We like to test our protected methods because some of them do contain logic. Now, if that method contain calls to other methods, we also want to verify that the call happened correctly. Verification though as far as I can tell only works with mock objects. We tried using PHPUnit_Extensions_Helper_AccessibleObject but it does not allow making the method public on these mocks. Can we add it, either by default or via a flag, the ability to automatically make a method public? So basically, we needed the ability to do the following (in very simple terms):

    class MyClass {
        ...
        protected function doWork($raw) {
            $data = $this->processRaw($raw);
            return array('result' => $data);
        }
        ...
    }

    class MyClassTest {
        public function testDoWork() {
            $mock = Phake::partialMock('MyClass');
            self::assert(array('result' => 'BLAH'), $mock->doWork('blah'));

            Phake::verify($mock)->processRaw(...);
        }
    }

**Comment by mlively** [comment]
This is now doable in the 2.1 branch. It's not really that much different from what mollierobbert posted, but it is at least code you don't have too write now. Documentation can be found here: http://phake.readthedocs.org/en/2.1/mocks.html#calling-private-and-protected-methods-on-mocks

**Comment by mollierobbert** [comment]
Great work Mike! Cheers.
