### ISSUE TITLE
Phake::verify not executing in finally block

### ISSUE THREAD

**Issue by lurkingrobbert** [mlively/Phake#160]
This works:

    $this->setExpectedException(Exception::class);

    try {
        $mock->callMethodThatThrowsException();
    }
    catch (Exception $e) {
        Phake::verify($mock)->someOtherInternalMethod(Phake::anyParameters());

        throw $e;
    }

This doesn't:

    $this->setExpectedException(Exception::class);

    try {
        $mock->callMethodThatThrowsException();
    }
    finally {
        Phake::verify($mock)->someOtherInternalMethod(Phake::anyParameters());
    }

In PHPUnit, both work. Is this a missing feature or simply impossible to mimick due to how PHPUnit works?

**Comment by mlively** [comment]
I could not reproduce. I used the following code:

            $this->setExpectedException("InvalidArgumentException");
            $mock = Phake::mock("PhakeTest_MockedClass");
            try
            {
                $mock->foo();
                throw new InvalidArgumentException();
            }
            finally
            {
                Phake::verify($mock)->foo();
            }

and it worked fine. If I commented out the call to $mock->foo() it fired an error like I would expect. Can you give me some more details on what you are seeing?

**Comment by lurkingrobbert** [comment]
I'm no longer able to reproduce the issue either. It's been a few months. Might have been a configuration error, or an issue with an earlier version.

Thanks for adding the test either way.
