### ISSUE TITLE
Problem invoking a method named "eval" on a mock

### ISSUE THREAD

**Issue by InvertedAcceleration** [mlively/Phake#164]
First things first, thanks for the hard work you put into `Phake`, it's great!

As for the issue, I'm trying to mock [`phpredis`](https://github.com/nicolasff/phpredis) and then use `verify`/`when` on it's [`eval`](https://github.com/nicolasff/phpredis#eval) method, which leads to some odd behaviour.  

I expected it to allow me to `verify`/`when` like I can with it's other methods, but instead it just throws the following exception any time `eval` is called on the mock:

```
RedisException: Redis server went away
```

Which is very strange as that's coming from the actual `phpredis` object, which I haven't instantiated.

I'm creating the mock like this:

```php
$this->redis = Phake::mock('redis');
```

I did dig around the `Phake` codebase and found `eval` in `reservedWords` inside the [`MockClass`](https://github.com/mlively/Phake/blob/master/src/Phake/ClassGenerator/MockClass.php#L109) which is no doubt the issue.  

As a quick test, I removed `eval` from the `reservedWords` array, but then invoking `eval` on the mock resulted in this:

```
Phake_ClassGenerator_MockClass::instantiate(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "redis_PHAKE547e744bc8771" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition
```

Is there a work around for this situation or could the code be updated to handle this?

**Comment by mlively** [comment]
I  have verified that with some recent serialization changes you can no mock redis in 2.0.0. Unfortunately I can't re-implement the eval function due to it being a reserved word. I am not sure this is fixable.
