### ISSUE TITLE
Facade::generateUniqueClassName generates invalid class names

### ISSUE THREAD

**Issue by tomzx** [mlively/Phake#176]
Under `cygwin`, it appears that `uniqid` will generate invalid class names (containing dot(s)). Either a different method should be used to generate unique names or stripping the dot(s) should be done.

http://php.net/manual/en/function.uniqid.php

```php
/* We can also activate the more_entropy parameter, which is 
 * required on some systems, like Cygwin. This makes uniqid()
 * produce a value like: 4b340550242239.64159797
 */
```

Example of generated class name: `Parser_PHAKE550d07b5aa4702.26570592`

**Comment by mlively** [comment]
Thanks, should be resolved now.
