### ISSUE TITLE
Method calls using makeVisible() / makeStaticVisible() don't return values

### ISSUE THREAD

**Issue by elazar** [mlively/Phake#179]
Looking at the code for [`VisibilityProxy`](https://github.com/mlively/Phake/blob/3112a75b7368e4852b2aa783045cbbb486af2e1a/src/Phake/Proxies/VisibilityProxy.php#L76-81) and [`StaticVisibilityProxy`](https://github.com/mlively/Phake/blob/3112a75b7368e4852b2aa783045cbbb486af2e1a/src/Phake/Proxies/StaticVisibilityProxy.php#L76-81), I can't tell what the issue is, but it appears that return values of any non-public methods executed using them are somehow lost.

If I change [these methods](https://github.com/mlively/Phake/blob/3112a75b7368e4852b2aa783045cbbb486af2e1a/tests/PhakeTest.php#L1622-1636) from `PhakeTest` to read as follows:

```php
public function testCallingProtectedMethods()
{   
    $mock = Phake::mock('PhakeTest_MockedClass');
    $returned = Phake::makeVisible($mock)->innerFunc();
    Phake::verify($mock)->innerFunc();
    $this->assertSame('test', $returned);
}   

public function testCallingProtectedStaticMethods()
{   
    $mock = Phake::mock('PhakeTest_StaticClass');
    $returned = Phake::makeStaticsVisible($mock)->protectedStaticMethod();
    Phake::verifyStatic($mock)->protectedStaticMethod();
    $this->assertSame('foo', $returned);
}
```

I get these failures:

```
1) PhakeTest::testCallingProtectedMethods
Failed asserting that null is identical to 'test'.
/home/matt/Documents/projects/presentations/phake/test/vendor/phake/phake/tests/PhakeTest.php:1628

2) PhakeTest::testCallingProtectedStaticMethods
Failed asserting that null is identical to 'foo'.
/home/matt/Documents/projects/presentations/phake/test/vendor/phake/phake/tests/PhakeTest.php:1637
```

The return values used in the changes above correspond to those from [`PhakeTest_MockedClass->innerFunc()`](https://github.com/mlively/Phake/blob/3112a75b7368e4852b2aa783045cbbb486af2e1a/tests/PhakeTest/MockedClass.php#L74-77) and [`PhakeTest_StaticClass->protectedStaticMethod()`](https://github.com/mlively/Phake/blob/3112a75b7368e4852b2aa783045cbbb486af2e1a/tests/PhakeTest/StaticClass.php#L53-56).

**Comment by mlively** [comment]
I will take a look. I fixed a similar issue recently that may have popped
back up in this area.

**Comment by mlively** [comment]
Actually it looks like this isn't a bug, but maybe the functionality isn't clearly explained?

The reason why the tests above are failing is because PhakeTest_MockedClass::innerFunc() and PhakeTest_StaticClass:: protectedStaticMethod() are both mocked with no stubs and therefore return null.

Using the following two tests cases works:

    public function testCallingProtectedMethods()
    {
        $mock = Phake::mock('PhakeTest_MockedClass');
        Phake::when($mock)->innerFunc()->thenCallParent();

        $returned = Phake::makeVisible($mock)->innerFunc();

        Phake::verify($mock)->innerFunc();
        $this->assertSame('test', $returned);
    }

    public function testCallingProtectedStaticMethods()
    {
        $mock = Phake::mock('PhakeTest_StaticClass');
        Phake::whenStatic($mock)->protectedStaticMethod()->thenCallParent();

        $returned = Phake::makeStaticsVisible($mock)->protectedStaticMethod();

        Phake::verifyStatic($mock)->protectedStaticMethod();
        $this->assertSame('foo', $returned);
    }

Can you verify the same? Any recommendations on improving the documentation would be welcome if you have them.

**Comment by elazar** [comment]
Thought that might be the case. I would suggest changing the wording in the [relevant documentation section](http://phake.readthedocs.org/en/2.1/mocks.html#calling-private-and-protected-methods-on-mocks) to reflect that the method is being stubbed, not just made visible for invocation without any modification. I read it the latter way rather than the former.

**Comment by mlively** [comment]
Documentation has been updated
