### ISSUE TITLE
Mocking Static Methods example generates E_STRICT error

### ISSUE THREAD

**Issue by elazar** [mlively/Phake#181]
[This line](https://github.com/mlively/Phake/blame/1c1561403379a3afd462782c32354edd9bce4834/docs/mocking-statics.rst#L27) causes this error in PHP >= 5.2:
 
```
Strict Standards: Static function StaticFactory::factory() should not be abstract
```

See: http://3v4l.org/hqR3a

**Comment by mlively** [comment]
Documentation updated. thanks
