### ISSUE TITLE
Stubbing __call() doesn't work

### ISSUE THREAD

**Issue by elazar** [mlively/Phake#182]
Here's a use case using the feature described in [this documentation section](http://phake.readthedocs.org/en/2.1/method-stubbing.html#stubbing-magic-methods) for stubbing `__call()` itself:

```php
class ClassWithCall {
    public function __call($method, $args) {
        return 42;
    }
}
$mock = \Phake::mock('ClassWithCall');
Phake::whenCallMethodWith('nonExistentMethod')
    ->isCalledOn($mock)->thenReturn(37);
var_dump($mock->nonExistentMethod());
```

I'd expect this to output `int(37)`, but instead it outputs `NULL`.

An equivalent test that stubs the method that triggers `__call()` instead of `__call()` itself appears to work as expected and returns `int(37)`:

```php
class ClassWithCall {
    public function __call($method, $args) {
        return 42;
    }
}
$mock = \Phake::mock('ClassWithCall');
Phake::when($mock)->nonExistentMethod()->thenReturn(37);
var_dump($mock->nonExistentMethod());
```

**Comment by mlively** [comment]
This was actually an error in the documentation. whenCallMethodName needs as many matchers as parameters __call() takes unless you use Phake::anyParameters() or Phake::ignoreRemaining()
