### ISSUE TITLE
Allow mocking methods with variadic arguments

### ISSUE THREAD

**Issue by mlively** [mlively/Phake#195]
Mocking a class which has a variadic method causes the following strict PHP error:

    Declaration of SOMECLASS_PHAKEabcdef123456::someMethod() should be compatible with SomeClass::someMethod(...$args)

**Comment by mollierobbert** [comment]
Any news on the 2.2 release? We can't wait :-).

**Comment by mlively** [comment]
Was working on getting one more feature in before I released 2.2. No need to make people wait though. I just rolled a tag. https://github.com/mlively/Phake/releases/tag/v2.2.0 I'll add a bit more detail to the release notes soon. Just wanted to get the tag out there for packagist.

**Comment by mollierobbert** [comment]
Awesome! Thanks Mike.
