### ISSUE TITLE
Disable constructor

### ISSUE THREAD

**Issue by silverpark** [mlively/Phake#201]
Hi,

It is possible to disable constructor with ``\Phake:partialMock`` like phpunit ?

Regards

**Comment by mlively** [comment]
This can currently be done using \Phake::mock('Your Class', Phake::ifUnstubbed()->thenCallParent());

This will essentially give you a mock that delegates to the mocked class without calling the constructor.

**Comment by silverpark** [comment]
Yes it work, thank you.

I would like to know, why have you the idea to create phake in start ?
