### ISSUE TITLE
Declaration should be compatible with Memcached

### ISSUE THREAD

**Issue by fire015** [mlively/Phake#214]
The following code:

    $memcached = Phake::mock('Memcached');

Throws this error:

    ErrorException: Declaration of Memcached_PHAKE56c729ed022311::get() should be compatible with Memcached::get($key, $cache_cb = NULL, &$cas_token = NULL, &$udf_flags = NULL)

Is there a workaround?

**Comment by mlively** [comment]
PHP extensions can be a bit finicky as they aren't necessarily required to be honest about their interface via reflection. Can you let me know which version of php and the memcached extension you are using and I can come with something for you that'll work. The output of both php -v and php --ri memcached would suffice

The only workaround until then would probably be to manually extend the class and define get and then call parent::get(...) (a pain I know.)

**Comment by fire015** [comment]
```
PHP 5.6.16 (cli) (built: Nov 26 2015 07:52:51)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

Memcached:

```
memcached support => enabled
Version => 2.2.0
libmemcached version => 1.0.16
SASL support => yes
Session support => yes
igbinary support => yes
json support => yes
msgpack support => yes

Directive => Local Value => Master Value
memcached.sess_locking => 1 => 1
memcached.sess_consistent_hash => no value => no value
memcached.sess_binary => no value => no value
memcached.sess_lock_wait => 150000 => 150000
memcached.sess_lock_max_wait => 0 => 0
memcached.sess_lock_expire => 0 => 0
memcached.sess_prefix => memc.sess.key. => memc.sess.key.
memcached.sess_number_of_replicas => 0 => 0
memcached.sess_randomize_replica_read => no value => no value
memcached.sess_remove_failed => 1 => 1
memcached.sess_connect_timeout => 1000 => 1000
memcached.sess_sasl_username => no value => no value
memcached.sess_sasl_password => no value => no value
memcached.compression_type => fastlz => fastlz
memcached.compression_factor => 1.3 => 1.3
memcached.compression_threshold => 2000 => 2000
memcached.serializer => igbinary => igbinary
memcached.use_sasl => no value => no value
memcached.store_retry_count => 2 => 2
```

**Comment by mlively** [comment]
I did some digging and it looks like this isn't anything I can control. Basically it boils down to an issue with memcached and the php extension api that makes it so you can't possibly match a signature.

https://github.com/php-memcached-dev/php-memcached/issues/126

I am adding some code that basically just hides the strict mode check when loading the mock. It isn't the best solution, but it is about all I can do at this point.

**Comment by fire015** [comment]
Thanks Mike
