### ISSUE TITLE
Question - method chaining

### ISSUE THREAD

**Issue by garethellis36** [mlively/Phake#215]
Hello,

First of all, thanks for a great library - it's a lot more pleasant to use than some other mocking APIs I have come across.

I am testing a class which calls a dependency's methods in chained fashion:
```php
$this->email->to($to)
    ->subject($subject)
    /*** other method calls ***/
    ->send();
```

Each method call returns the instance of the dependency (i.e. `return $this`).

Is there a less verbose way of setting up the return values of the stubs? As it is, I have a line like this for each method call, which becomes something of a pain :-)
```php
Phake::when($mockEmail)->to($this->anything())->thenReturn($mockEmail);
```

Is there any API available to do something like this?
```php
Phake::when($mockEmail)->anyMethodCall()->thenReturnSelf();
```

I couldn't see it in the documentation, but maybe I was looking in the wrong place.

**Comment by mlively** [comment]
Hmm, surprisingly I don't have that ability! I'll look at getting it added fairly quickly. I do have the ability to set a default stub, but only at the time you create the mock: http://phake.readthedocs.org/en/2.1/method-stubbing.html#setting-default-stubs

So it can't be used to return one's self :(.

This'll be an easy add thoguh. I'll get it into the next version.

**Comment by garethellis36** [comment]
Thanks! :+1:
