### ISSUE TITLE
Cannot use "self" return type in mocked class

### ISSUE THREAD

**Issue by mariusz-kraj-c** [mlively/Phake#226]
I created entity class:

    class User {
        public function setName(string $name) : self {
            $this->name = $name;
            return $this;
        }
    }

Then in test tried to create mock by

    $userMock = \Phake::mock(User::class);

but test execution just halt at that line without any error. After some investigation i found out that mock content created by phake contains something like that:

    /**
     * @param string $name
     *
     * @return User
     */
    public function setName(string $name) : self
    {
        $__PHAKE_args = array();
        $funcGetArgs = func_get_args();
        $__PHAKE_numArgs = count($funcGetArgs);
        if (0 < $__PHAKE_numArgs) $__PHAKE_args[] =& $refund;
        for ($__PHAKE_i = 1; $__PHAKE_i < $__PHAKE_numArgs; $__PHAKE_i++) $__PHAKE_args[] = func_get_arg($__PHAKE_i);

        $__PHAKE_info = Phake::getInfo($this);
        if ($__PHAKE_info === null) {
            return null;
        }

        $__PHAKE_funcArgs = func_get_args();
        $__PHAKE_answer = $__PHAKE_info->getHandlerChain()->invoke($this, 'addRefund', $__PHAKE_funcArgs, $__PHAKE_args);

        $__PHAKE_callback = $__PHAKE_answer->getAnswerCallback($this, 'addRefund');

        if ($__PHAKE_callback instanceof Phake_Stubber_Answers_ParentDelegateCallback)
        {
            $__PHAKE_result = $__PHAKE_callback($__PHAKE_args);
        }
        else
        {
            $__PHAKE_result = call_user_func_array($__PHAKE_callback, $__PHAKE_args);
        }
        $__PHAKE_answer->processAnswer($__PHAKE_result);
        return $__PHAKE_result;
    }

the issue is that "self" mean in my case "User_PHAKE58319e767bab31" so the declaration is incompatibile with User class.

The simples fix (that I uses) is to explicy use "User" as return value. 

I don't know if this is real issue but I wanted to save someone time searching for fix :)

**Comment by mlively** [comment]
Good find. This is definitely fixable.

**Comment by Daanvm** [comment]
I ran into this issue as well, I've created PR #254 to fix this.
