### ISSUE TITLE
PHPUnit 6 is not compatible!

### ISSUE THREAD

**Issue by fattouchsquall** [mlively/Phake#236]
I can't run Phake under PHP6 client.

**Comment by 20uf** [comment]
PHP6 ? :-)

**Comment by fattouchsquall** [comment]
Yes PHPUnit 6 :+1:

**Comment by garak** [comment]
I'm using Phake with phpunit 6.0.8, but current requirements don't allow for newer versions.
This is cause by requiring sebastian/comparator ~1.1 (while latest phpunit requires ^2.0)

**Comment by willemstuursma** [comment]
I've got some errors with `Error: Class 'PHPUnit_Framework_Assert' not found`.

**Comment by fkandus-olx** [comment]
I also get `Error: Class 'PHPUnit_Framework_Assert' not found`. This happened when I added `Phake::setClient(Phake::CLIENT_PHPUNIT);` to remove the "risky" label from tests that were only doing verify and no phpUnit assertions.

**Comment by fattouchsquall** [comment]
This PR will resolve this issue: https://github.com/mlively/Phake/pull/235

**Comment by mlively** [comment]
This is now resolved by #235 being merged
