### ISSUE TITLE
Fatal error when mocking a final class

### ISSUE THREAD

**Issue by Smitsel** [mlively/Phake#237]
When mocking a final class you get a fatal error:

When i have a final class like:
```
<?php

final class FinalClass
{

}
```
And mock it by using:
```
Phake::mock('FinalClass');
```

We get a fatal error:
    Class NewClass may not inherit from final class (FinalClass) in /var/www/Phake/src/Phake/ClassGenerator/EvalLoader.php(58) : eval()'d code on line 3

Proposal:
We could change it so it throws a better custom error exception

**Comment by mlively** [comment]
Makes sense, it should be trivial to see that the class being mocked is
final then just throw an exception as opposed to dying completely
