### ISSUE TITLE
Verifying method invocation does not fail on TypeError

### ISSUE THREAD

**Issue by Glutexo** [mlively/Phake#252]
Say we have a class like this:

```php
class MyClass
{
    public function myMethod(stdClass $myParameter)
    {
        //
    }
}
```

and a test like this:

```php
$mock = Phake::mock(MyClass::class);
try {
    $mock->myMethod(null);
} catch(TypeError $error) {
    //
}
Phake::verify($mock)->myMethod(Phake::never());
```

The test passes, even though we tried to invoke the method. I am not sure whether this is a wanted behavior. It is true, that the method has not been actually called, because the call resulted in throwing the _TypeError_. On the other hand, there **was** a try* to call the method.

The _try/catch_ part can be hidden. For example in a web framework, any exception/error in a controller may be caught and converted to a valid HTTP response. Then, a test verifying that some method call does not happen still succeeds: not because of a correct logic, but because of the caught error. This can be “solved” by verifying something that ought to happen _after_ the verified method call. (E.g. a successful response in the before mentioned example of a web framework.) But this can introduce another misconceptions and is definitely a not a good way to have an atomic test.

I am not familiar with _Phake_ internals. Thus, even if it was considered useful to implement this behavior, I am not sure, whether it is technically possible. It would require to change signature of the overridden method and that might not be a good/possible thing to do. Just throwing in for consideration.

**Comment by adoy** [comment]
This is the expecte behaviour. PHP do not actually call the method but throws the TypeError instead. Even if we wanted to change this (which is not the case), there is nothing that we could do about this. 

Thanks anyway for opening this issue !
