### ISSUE TITLE
`thenReturnCallback()` doesn't cause mock to return a value

### ISSUE THREAD

**Issue by Danonk** [mlively/Phake#255]
```php
class Dupa {
    public function foo(int $a) {
        return $a;
    }
}
```
```php
$mock = Phake::mock(Dupa::class);
Phake::when($mock)->foo()->thenReturnCallback(function ($val) { return $val * 2; });

$this->assertEquals(42, $mock->foo(21));
```

Causes:
```
Failed asserting that null matches expected 42.
Expected :42
Actual   :null
```
The callback isn't even invoked

**Comment by mlively** [comment]
This is happening in this case because the parameter of your stub (empty)
doesn't match the parameter you made the call with (21). Change the stub to
Phake::when($mock)->foo->thenReturnCallback(). I will check when I get a
moment to make sure that was the only issue, but that could be the issue.

**Comment by adoy** [comment]
I guess this was the problem since no answer since 2017.
Closing this issue.
