### ISSUE TITLE
PHPUnit 7 Compatibility

### ISSUE THREAD

**Issue by beberlei** [mlively/Phake#257]
Running the PHPUnit nightly with Phake gives a Fatal Error:

```
Fatal error: Declaration of Phake_PHPUnit_VerifierResultConstraintV6::matches($other) must be compatible with PHPUnit\Framework\Constraint\Constraint::matches($other): bool in /var/www/xhprof/vendor/phake/phake/src/Phake/PHPUnit/VerifierResultConstraintV6.php on line 74
```

**Comment by pps1** [comment]
`Phake_PHPUnit_VerifierResultConstraintV6::toString()` and `Phake_PHPUnit_VerifierResultConstraintV6::failureDescription()` are incompatible as well.

**Comment by pps1** [comment]
This is patched here:
https://github.com/pps1/Phake/commit/cf0e741c201742c7520fdced18d070767d5f4f66

Happy to open a PR if you'd like.

**Comment by bfeaver** [comment]
@pps1 If you could open that PR, I'd be happy to take a look at it.

**Comment by strider2038** [comment]
@bfeaver can you make a release tag? https://github.com/mlively/Phake/releases

**Comment by bfeaver** [comment]
v3.1.0 released with PHPUnit 7 compatibility
