### ISSUE TITLE
ReflectionType::__toString() is deprecated in PHP 7.4

### ISSUE THREAD

**Issue by slt** [mlively/Phake#279]
ReflectionType::__toString() is deprecated in PHP 7.4

This is causing issues with both:
src/Phake/ClassGenerator/MockClass.php 
src/Phake/Stubber/Answers/SmartDefaultAnswer.php

**Comment by strider2038** [comment]
@bfeaver this issue blocks us to upgrate to PHP 7.4. When can you merge fix?

**Comment by vasily-kartashov** [comment]
https://www.php.net/manual/en/reflectionnamedtype.getname.php requires PHP 7.1, so composer.json needs to be updated. As is the version 3.1.7 breaks builds on PHP 7.0
