### ISSUE TITLE
Feature suggestion: throwOrReturn()

### ISSUE THREAD

**Issue by JKingweb** [mlively/Phake#283]
A lot of my test cases end up looking something like this:

```php
if ($output instanceof \Exception) {
    \Phake::when($mock)->method->thenThrow($output);
} else {
    \Phake::when($mock)->method->thenReturn($output);
}
```

If would be nice if it could simply be:

```php
\Phake::when($mock)->method->thenThrowOrReturn($output);
```

**Comment by adoy** [comment]
Hi and Thanks for the suggestions. I don't think this is something that we want to add in Phake. Those are two really different behaviour and I don't think they should be mixed.

Thanks for the suggestion.
